### ISSUE TITLE
Styling of title

### ISSUE THREAD

**Issue by DeHeeeb** [Kifkof/quotes#12]
**Is your feature request related to a problem? Please describe.**
Currently it is hard to notice that the title "Quotes 2.0" in the upper right corner is clickable.

**Describe the solution you'd like**
To improve that, the title should be redesigned.

**Additional context**
- mouse hover should be different
- text shouldn't be selectable

**wont implement**
- clicking on it should reload the overview page

**Comment by cosimo-augustoni** [comment]
we want to implement live reload in the future, so the reload over the title isnt as useful. We dont want to implement an event service to refresh the quotes list right now
