### ISSUE TITLE
Date format of quote wrong

### ISSUE THREAD

**Issue by cosimo-augustoni** [Kifkof/quotes#4]
**Describe the bug**
The format of the "date of quote" is dd/MM/yyyy hh:mm:ss on some machines format

**To Reproduce**
1. Go to https://quotes.kallisto.li/
2. Look at the date of a quote

**Expected behavior**
1. The time part is removed.
2. The format is displayed either as dd.MM.yyyy or dependen on the culture of the user

**Comment by DeHeeeb** [comment]
@Kifkof
I believe the current date format is actually MM/dd/yyyy
